// Array de productos

const productos = [
    {id:1 ,
        nombre:"Fideos",
        precio: 1000,
        descripcion:"Fideos italianos tallarines",
        cantidad: 0,
    },
    {id:2 ,
        nombre:"Arroz",
        precio: 800,
        descripcion:"Arroz largo doble carolina",
        cantidad:0,
    },
    {id:3 ,
        nombre:"Aceite",
        precio: 1100,
        descripcion:"Aceite de oliva Extra virgen",
        cantidad:0,
    },
    {id:4 ,
        nombre:"Mermelada",
        precio: 1300,
        descripcion:"Mermelada dew frutos rojos",
        cantidad:0,
    },
    {id:5 ,
        nombre:"Yerba",
        precio: 750,
        descripcion:"Yerba naturald despalada",
        cantidad:0,
    }
    ];